name: UltraCaptureTheWool
main: io.github.Leonardo0013YT.UltraCTW.UltraCTW
version: 2.5.0
author: Leonardo0013YT
description: UltraCTW edited by MGDCl
softdepend: [ PlaceholderAPI ]
depend: [ NametagEdit, ProtocolLib, WorldEdit, FastAsyncWorldEdit ]
commands:
  stats:
  ctws:
    aliases: [ ctwadmin ]
  ctw:
    aliases: [ dcl ]
  leave:
    aliases: [ salir ]
  join:
    aliases: [ jugar ]
  shout:
    aliases: [ global, g, grito]